//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizmint
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentAnswer
    {
        public int Id { get; set; }
        public int AssignmentId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> UserSelectedAnswerId { get; set; }
        public Nullable<bool> UserSelectedTrue { get; set; }
        public string UserEnteredText { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Question Question { get; set; }
    }
}
